app:
  eureka-username: admin
  eureka-password: admin
  eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka-username}:${app.eureka-password}@${app.eureka-server}:8761/eureka/"
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092    
    
spring.rabbitmq:  
   host: 127.0.0.1  
   port: 5672  
   username: guest  
   password: guest
   
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"     
---    
spring:
  profiles: docker
app.eureka-server: eureka
app.auth-server: authserver
spring.rabbitmq.host: rabbitmq
spring.cloud.stream.kafka.binder.brokers: kafka  