server:
  port: 7001
server.error.include-message: always

spring.application.name : "product"

spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db
  
spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup

spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
---    
spring:
  profiles: docker
spring.data.mongodb.host: mongodb  
  
server:
  port: 8080   
    